language: java
jdk:
  - openjdk6
  - oraclejdk8
install:
  - jdk_switcher use openjdk6 && export JAVA6_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8 && export JAVA8_HOME=$JAVA_HOME
  - ./gradlew check